version: '3.8'
services:
  db:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: mydb
    volumes:
      - pgdb:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: 'tables-filter tinymce'
    depends_on:
      - db
  pgweb:
    image: sosedoff/pgweb
    restart: always
    ports:
      - 8081:8081
    environment:
      DATABASE_URL: postgres://root:changeme@db:5432/mydb?sslmode=disable
    depends_on:
      - db

volumes:
  pgdb:
    driver: local
